default_context:
  project_name: 'Offline App'
  project_slug: 'offline-app'
  domain_main: 'offline-app.com'
  domain_staging: 'stag.offline-app.com'
  docker_swarm_stack_name_main: 'offline-app-com'
  docker_swarm_stack_name_staging: 'stag-offline-app-com'
  secret_key: 'da41d8b1eda63060c8d699f66e6fc47ea4551ae3d6098aa62a465c14ef8455bd'
  first_superuser: 'admin@offline-app.com'
  first_superuser_password: 'Password123$'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.offline-app.com, https://stag.offline-app.com, https://offline-app.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@offline-app.com'
  postgres_password: '795b6cf9664ad956cd3e9b5804d6a9af8bbaf5115904944cd05debd518f1f274'
  pgadmin_default_user: 'admin@offline-app.com'
  pgadmin_default_user_password: 'Password123$'
  traefik_constraint_tag: 'offline-app.com'
  traefik_constraint_tag_staging: 'stag.offline-app.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Password123$'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
