"""Add indexes

Revision ID: 11c0c81bdf41
Revises: 484242ef1abe
Create Date: 2019-09-12 09:15:33.709447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c0c81bdf41'
down_revision = '484242ef1abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_name', table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.drop_index('ix_city_name', table_name='city')
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=True)
    op.drop_index('ix_resourcetype_name', table_name='resourcetype')
    op.create_index(op.f('ix_resourcetype_name'), 'resourcetype', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resourcetype_name'), table_name='resourcetype')
    op.create_index('ix_resourcetype_name', 'resourcetype', ['name'], unique=False)
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.create_index('ix_city_name', 'city', ['name'], unique=False)
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    # ### end Alembic commands ###
