"""add assignee to resources

Revision ID: b198a5f3a2c5
Revises: c60f860aa962
Create Date: 2019-09-14 14:18:40.923409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b198a5f3a2c5'
down_revision = 'c60f860aa962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource', 'user', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column('resource', 'assignee_id')
    # ### end Alembic commands ###
